<?php $codeSamples = new RAML2HTML\codeSamples($RAML);  error_reporting(0);?>
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title><?php echo $RAML->title; ?> </title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="www.agonxheladini.com">
  <link rel="stylesheet" href="templates/ePaisa_scrol/css/uikit.css">
  <link rel="stylesheet" href="templates/ePaisa_scrol/css/custom.css">
  <link rel="stylesheet" href="templates/ePaisa_scrol/highlight/styles/monokai-sublime.css">
  <script type="text/javascript" src="templates/ePaisa_scrol/js/jquery-3.2.1.min.js"></script>
  <script type="text/javascript" src="templates/ePaisa_scrol/js/custom.js"></script>
  <script type="text/javascript" src="templates/ePaisa_scrol/js/uikit.min.js"></script>
  <script type="text/javascript" src="templates/ePaisa_scrol/js/uikit-icons.min.js"></script>
  <script type="text/javascript" src="templates/ePaisa_scrol/js/jquery.scrollNav.js"></script>
  <script type="text/javascript" src="templates/ePaisa_scrol/highlight/highlight.pack.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>

  <script src="//cdn.jsdelivr.net/jquery.scrollto/2.1.2/jquery.scrollTo.min.js"></script>
  <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->
</head>
<body>
  <div id="left_part">
       <header class="header">
           <div class="logo" style="padding: 10px 0 12px 0; margin-right: 37px;">
            <a href="<?php echo $_SERVER['PHP_SELF']; ?>">
             <img src="templates/ePaisa_scrol/images/ePaisa_logo.png">
            </a>
      </header>
      <div id="menu_holder">
        <?php  include('_menu.phtml');?>
      </div>
  </div>
  <div id="right_content">


   <!-- <div id="content_nav">
        <div class="search_box">
           <div class="icon_box">
             <span uk-icon="icon: search; ratio: 1"></span>
           </div>
           <div class="input_box">
             <input type="text" name="search" placeholder="Search documentation..." class="search_input">
           </div>
        </div>
        <div class="top_menu_box">

           <nav class="uk-navbar-container" uk-navbar>
              <div class="uk-navbar-left">
                  <ul class="uk-navbar-nav">
                      <li class="uk-parent"><a href="https://support.epaisa.com" target="blank">Support</a></li>
                      <li class="uk-parent"><a href="https://secure.epaisa.com/" target="blank">Sign in <span uk-icon="icon: arrow-right; ratio: 1" style="margin-top:4px;"></span></a></li>
                  </ul>
              </div>
            </nav>

        </div>
        <div class="menu_icon">
           <span uk-icon="icon: menu; ratio: 1"></span>
        </div>
    </div>-->
    <div  id="main-content">
          
     <?php 
     
         $full_cats = $RAML->getChildPaths('/');
         sort($full_cats);
         $count_full_cats = count($full_cats);

          for ($i = 0; $i < $count_full_cats; $i++)
          {
            $menu_item = GetBetween("/","/", $full_cats[$i]);
            $main_cats[$menu_item][] = $full_cats[$i];    
          }
     
          $final_cats =  json_encode($main_cats);
         $html = "";
         foreach($full_cats as $endpoint => $resource) {
            
            

            $RAML->setCurrentPath($resource); 
            $current_path =  $RAML->baseUri . $RAML->getCurrentPath();
            $desc = $RAML->path()->description;
           
            $sub_cats_final = str_replace('/', '', $resource);

          $html .= "<div class='endpoint_holder post__article' id='$sub_cats_final'>";
            
              $html .= "<div class='left_part'>";
                   $html .= "<div class='uk-container'>";
                     
                           $html .= "<h5 class='uk-heading-bullet'>".$current_path."</h5>";
                           $html .= "<div class='uk-placeholder'>".$desc."</div>";
                           $html .= '<div class="uk-tile uk-tile-muted uk-padding-remove"><h3 class="uk-heading-bullet">Available Actions</h3></div>';

                            $verbs = "<ul class='uk-subnav uk-subnav-pill' uk-switcher>";
                            foreach ($RAML->path()->getVerbs() as $verb){ 
               
                              $verbs .= "<li><a href='#''>".$verb."</a></li>";
               
                              }
                             $verbs .="</ul>";

                             $verb_content = "<ul class='uk-switcher uk-margin'>";
             
             foreach ($RAML->path()->getVerbs() as $verb_con) { 
               
              $description = RAML2HTML\markdown::clean($RAML->path()->get($verb_con)->get('description'));
              $verb_content .= "<li><div class='uk-placeholder'>".$description."</div>";
              
               $RAML->setCurrentAction($verb_con);

/* COPY STARTS HERE */
/*
     if ($RAML->action()->get('queryParameters')->isArray()):
                    
     $verb_content .= "<table class='uk-table uk-table-striped'><caption><h3 class='uk-heading-bullet'>Query Parameters</h3></caption>";
     $verb_content .= "<thead><tr><th>Parameter</th><th>Type</th><th>Required</th><th>Description</th></tr></thead>";
     foreach ($RAML->action()->get('queryParameters')->toArray() as $param => $details) {
     
     $required = (isset($details['required']) && $details['required'] == 1 ? 'Yes' : '');
   
     if (isset($details['example'])) {
      $example_final = "<span style='display: block; margin: 6px 0 8px 0; border-top: 1px solid #aaa; color: #666; padding: 4px; font-size: 10px;''><b>Example:</b>".$details['example'].'</span>';
     }else { $example_final = " ";}

     if (isset($details['type'])) { $type = $details['type']; } else { $type = " "; }
     if (isset($details['description'])) { $desc_details = $details['description']; } else { $desc_details = " "; }


     $verb_content.="<tr><td>".$param."</td><td>".$type."</td><td>".$required."</td><td>{{ needs a fix }}</span>".$example_final."</td></tr>";
  }
  $verb_content .= "</table>";

     endif;

     if ($RAML->action()->get('body')->get('application/x-www-form-urlencoded')->get('formParameters')->isArray()):
                    
     $verb_content .= "<table class='uk-table uk-table-striped'><caption>Form Parameters</caption>";
     $verb_content .= "<thead><tr><th>Parameter</th><th>Type</th><th>Required</th><th>Description</th></tr></thead>";
     foreach ($RAML->action()->get('queryParameters')->toArray() as $param => $details) {

      $required = (isset($details['required']) && $details['required'] == 1 ? 'Yes' : '');
   
     if (isset($details['example'])) {
      $example_final = "<span style='display: block; margin: 6px 0 8px 0; border-top: 1px solid #aaa; color: #666; padding: 4px; font-size: 10px;''><b>Example:</b>".$details['example'].'</span>';
     }else { $example_final = " ";}

     if (isset($details['type'])) { $type = $details['type']; } else { $type = " "; }
     if (isset($details['description'])) { $desc_details = $details['description']; } else { $desc_details = " "; }


     $verb_content.="<tr><td>".$param."</td><td>".$type."</td><td>".$required."</td><td>{{ needs a fix }}</span>".$example_final."</td></tr>";


     }

     $verb_content .= "</table>";

     endif;

     if ($RAML->action()->get('body')->get('application/json')->get('schema')->get('properties')->isArray()):
                    
     $verb_content .= "<table class='uk-table uk-table-striped'><caption>Form Parameters</caption>";
     $verb_content .= "<thead><tr><th>Parameter</th><th>Type</th><th>Required</th><th>Description</th></tr></thead>";

     $tmp = $RAML->action()->get('body')->get('application/json')->get('schema')->toArray();
  if ($RAML->action()->get('body')->get('application/json')->get('schema')->isString()) {
    $tmp = json_decode($RAML->action()->get('body')->get('application/json')->get('schema')->toString(), true);
  }

  foreach ($tmp['properties'] as $param => $details) {

     $required = (isset($details['required']) && $details['required'] == 1 ? 'Yes' : '');
   
     if (isset($details['example'])) {
      $example_final = "<span style='display: block; margin: 6px 0 8px 0; border-top: 1px solid #aaa; color: #666; padding: 4px; font-size: 10px;''><b>Example:</b>".$details['example'].'</span>';
     }else { $example_final = " ";}

     if (isset($details['type'])) { $type = $details['type']; } else { $type = " "; }
     if (isset($details['description'])) { $desc_details = $details['description']; } else { $desc_details = " "; }


     $verb_content.="<tr><td>".$param."</td><td>".$type."</td><td>".$required."</td><td>{{ needs a fix }}</span>".$example_final."</td></tr>";

     }

     $verb_content .= "</table>";

    endif;
    //** Query parameters table ends here **///  
   
   //** Form parameters table starts here **///  
   /* if ($RAML->action()->get('body')->get('application/x-www-form-urlencoded')->get('formParameters')->isArray()):
                    
     $verb_content .= "<table class='uk-table uk-table-striped'><caption>Form Parameters</caption>";
     $verb_content .= "<thead><tr><th>Parameter</th><th>Type</th><th>Required</th><th>Description</th></tr></thead>";
     foreach ($RAML->action()->get('queryParameters')->toArray() as $param => $details) {

      $required = (isset($details['required']) && $details['required'] == 1 ? 'Yes' : '');
   
     if (isset($details['example'])) {
      $example_final = "<span style='display: block; margin: 6px 0 8px 0; border-top: 1px solid #aaa; color: #666; padding: 4px; font-size: 10px;''><b>Example:</b>".$details['example'].'</span>';
     }else { $example_final = " ";}

     if (isset($details['type'])) { $type = $details['type']; } else { $type = " "; }
     if (isset($details['description'])) { $desc_details = $details['description']; } else { $desc_details = " "; }


     $verb_content.="<tr><td>".$param."</td><td>".$type."</td><td>".$required."</td><td>{{ needs a fix }}</span>".$example_final."</td></tr>";


     }

     $verb_content .= "</table>";

     endif;
     //** Form parameters table table ends here **/// 
    
    //** JSON Parameters table starts here **/// 
   /* if ($RAML->action()->get('body')->get('application/json')->get('schema')->get('properties')->isArray()):
                    
     $verb_content .= "<table class='uk-table uk-table-striped'><caption>JSON Parameters</caption>";
     $verb_content .= "<thead><tr><th>Parameter</th><th>Type</th><th>Required</th><th>Description</th></tr></thead>";

     $tmp = $RAML->action()->get('body')->get('application/json')->get('schema')->toArray();
  if ($RAML->action()->get('body')->get('application/json')->get('schema')->isString()) {
    $tmp = json_decode($RAML->action()->get('body')->get('application/json')->get('schema')->toString(), true);
  }

  foreach ($tmp['properties'] as $param => $details) {

     $required = (isset($details['required']) && $details['required'] == 1 ? 'Yes' : '');
   
     if (isset($details['example'])) {
      $example_final = "<span style='display: block; margin: 6px 0 8px 0; border-top: 1px solid #aaa; color: #666; padding: 4px; font-size: 10px;''><b>Example:</b>".$details['example'].'</span>';
     }else { $example_final = " ";}

     if (isset($details['type'])) { $type = $details['type']; } else { $type = " "; }
     if (isset($details['description'])) { $desc_details = $details['description']; } else { $desc_details = " "; }


     $verb_content.="<tr><td>".$param."</td><td>".$type."</td><td>".$required."</td><td>{{ needs a fix }}</span>".$example_final."</td></tr>";

     }

     $verb_content .= "</table>";

    endif;

/* COPY ENDS HERE */
    //** JSON Parameters table ends here **///
               
    //** Code Samples starts here **///
    $codeSamples = new RAML2HTML\codeSamples($RAML);
    $verb_content .= '<div class="uk-tile uk-tile-muted uk-padding-remove"><h3 class="uk-heading-bullet" style="margin-bottom:20px !important;">Code Samples</h4></div>';
       
    $js_code = str_replace("\n", "<br />", $codeSamples->javascript());
    $php_code = str_replace("\n", "<br />", $codeSamples->php());
    $rails_code = str_replace("\n", "<br />", $codeSamples->rails());
    

    $verb_content .= "<ul class='uk-subnav uk-subnav-pill' uk-switcher>";
    $verb_content .= "<li><a href='#''> PHP </a></li>";
    $verb_content .= "<li><a href='#''> JavaScript </a></li>";
    $verb_content .= "<li><a href='#''> Rails </a></li>";
    $verb_content .= "</ul>";


    $verb_content .= "<ul class='uk-switcher uk-margin'>";
    $verb_content .= "<li><pre><code class='php hljs'>".$php_code."</code></pre></li>";
    $verb_content .= "<li><pre><code class='javascript hljs'>".$js_code."</code></pre></li>";
    $verb_content .= "<li><pre><code class='php hljs'>".$rails_code."</code></pre></li>";
    $verb_content .= "</ul>";

    //** Code Samples starts here **///
    
    //** JSON Response starts here  **///
    $verb_content .= '<div class="uk-tile uk-tile-muted uk-padding-remove"><h3 class="uk-heading-bullet" style="margin-bottom:20px !important;">Response</h3></div>';  

   foreach ($RAML->path()->getResponses() as $code => $responses) 
   {
      $verb_content .= $code;
      foreach ($responses as $response) {
         if (in_array($response['type'], array('example', 'schema'))) {
        continue;
      }

     $verb_content .= ': <span class="responseText">' . (is_array($response['type']) ? array_shift($response['type']) : $response['type']) . '</span>';

     if (isset($response['example'])):
       
       $verb_content .= "<pre><code class='json hljs'>".$response['example']."</code></pre>";

      endif;

      }
   }
   //** JSON Response ends here **///

    $verb_content .= "</li>";
     }

          

$verb_content .="</ul>";

$html .= $verbs;
$html .= $verb_content;


              $html .= "</div>";
              $html .= "</div>";

              $html .= "<div class='right_part'>";
                   $html .= "<div class='uk-container'>";

                   $html .= "</div>";
              $html .= "</div>";

            $html .= "</div>";



    
            /*echo "<div class='endpoint_holder post__article' id='$sub_cats_final'>";

               

              echo "<div class='left_part'>";      
                echo "<div class='uk-container'>";
                   echo $resource."<br>";
                   echo "Add this class, if you do not want to limit the container width but still want the dynamic horizontal padding.";
                echo "</div>";             
              echo "</div>";

              echo "<div class='right_part'>"; 
                 echo "<div class='uk-container'>";

                 echo "</div>";
              echo "</div>";


            echo "</div>";*/

          }
     echo $html;
     ?>  


    </div>
  </div>
</body>

</html>


